apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-core-binding
  namespace: fltenant1 # kpt-set: ${tenant-name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer-core
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: someuser@example.com # kpt-set: ${tenant-developer}
