apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa
  namespace: fltenant1 # kpt-set: ${tenant-name}
  annotations:
    # Workload Identity
    iam.gke.io/gcp-service-account: tp-w-fltenant1-apps-sa@driven-density-457716-m7.iam.gserviceaccount.com # kpt-set: ${gcp-service-account}
